spring:
  application:
    name: faqs
  datasource:
    url: jdbc:postgres://localhost:5432/faqsdatabase
    password: secret
    username: admin
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo #gpt-4o
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: cosine_distance
        dimensions: 1536
        initialize-schema: false
  docker:
    compose:
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true



